AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Spring Lambda written with SpringBoot with the aws-serverless-java-container library

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  SpringLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.serverless.sample.springboot3.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 256
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Architectures:
        - x86_64
      SnapStart:
        ApplyOn: PublishedVersions
      AutoPublishAlias: "live"
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'

Outputs:
  SpringLambdaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: SpringLambdaApi
