spring:
  datasource:
    url: jdbc:p6spy:postgresql://${DB_HOST:localhost}:5432/spring-lambda
    username: ${DB_LOGIN:spring-lambda}
    password: ${DB_PASSWORD:spring123}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        highlight_sql: true
        generate_statistics: false
        jdbc:
          batch_size: 300
        order_updates: true
        order_inserts: true
      hibernate.format_sql: true

  flyway:
    fail-on-missing-locations: true
    locations: db/migration/common
    enabled: false
